// Auto-generated enum validators for chittyledger
// DO NOT EDIT - Generated by chittyschema

/**
 * Enum: blockchain_network
 */
export enum BlockchainNetwork {
  ETHEREUM_MAINNET = 'ETHEREUM_MAINNET',
  ETHEREUM_SEPOLIA = 'ETHEREUM_SEPOLIA',
  POLYGON = 'POLYGON',
  BASE = 'BASE',
  LOCAL_TESTNET = 'LOCAL_TESTNET',
}

/**
 * Enum: case_type
 */
export enum CaseType {
  DIVORCE = 'DIVORCE',
  CUSTODY = 'CUSTODY',
  CIVIL = 'CIVIL',
  CRIMINAL = 'CRIMINAL',
  PROBATE = 'PROBATE',
}

/**
 * Enum: classification_level
 */
export enum ClassificationLevel {
  FACT = 'FACT',
  SUPPORTED_CLAIM = 'SUPPORTED_CLAIM',
  ASSERTION = 'ASSERTION',
  ALLEGATION = 'ALLEGATION',
  CONTRADICTION = 'CONTRADICTION',
}

/**
 * Enum: event_severity
 */
export enum EventSeverity {
  DEBUG = 'DEBUG',
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

/**
 * Enum: event_type
 */
export enum EventType {
  USER_ACTION = 'USER_ACTION',
  SYSTEM_EVENT = 'SYSTEM_EVENT',
  API_CALL = 'API_CALL',
  SERVICE_INTERACTION = 'SERVICE_INTERACTION',
  ERROR = 'ERROR',
  SECURITY = 'SECURITY',
  AUDIT = 'AUDIT',
  INTEGRATION = 'INTEGRATION',
}

/**
 * Enum: evidence_tier
 */
export enum EvidenceTier {
  SELF_AUTHENTICATING = 'SELF_AUTHENTICATING',
  GOVERNMENT = 'GOVERNMENT',
  FINANCIAL_INSTITUTION = 'FINANCIAL_INSTITUTION',
  INDEPENDENT_THIRD_PARTY = 'INDEPENDENT_THIRD_PARTY',
  BUSINESS_RECORDS = 'BUSINESS_RECORDS',
  FIRST_PARTY_ADVERSE = 'FIRST_PARTY_ADVERSE',
  FIRST_PARTY_FRIENDLY = 'FIRST_PARTY_FRIENDLY',
  UNCORROBORATED_PERSON = 'UNCORROBORATED_PERSON',
}

/**
 * Enum: evidence_type
 */
export enum EvidenceType {
  DOCUMENT = 'Document',
  IMAGE = 'Image',
  COMMUNICATION = 'Communication',
  FINANCIAL_RECORD = 'Financial Record',
  LEGAL_FILING = 'Legal Filing',
  PHYSICAL_EVIDENCE = 'Physical Evidence',
}

/**
 * Enum: fact_type
 */
export enum FactType {
  DATE = 'DATE',
  AMOUNT = 'AMOUNT',
  ADMISSION = 'ADMISSION',
  IDENTITY = 'IDENTITY',
  LOCATION = 'LOCATION',
  RELATIONSHIP = 'RELATIONSHIP',
  ACTION = 'ACTION',
  STATUS = 'STATUS',
}

/**
 * Enum: subscription_status
 */
export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  TRIAL = 'TRIAL',
}

/**
 * Enum: transaction_status
 */
export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
}

/**
 * Enum: transaction_type
 */
export enum TransactionType {
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  INVOICE = 'INVOICE',
  SUBSCRIPTION = 'SUBSCRIPTION',
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  FEE = 'FEE',
  ADJUSTMENT = 'ADJUSTMENT',
}

/**
 * Enum: user_type
 */
export enum UserType {
  PARTY_PETITIONER = 'PARTY_PETITIONER',
  PARTY_RESPONDENT = 'PARTY_RESPONDENT',
  ATTORNEY_PETITIONER = 'ATTORNEY_PETITIONER',
  ATTORNEY_RESPONDENT = 'ATTORNEY_RESPONDENT',
  COURT_OFFICER = 'COURT_OFFICER',
  EXPERT_WITNESS = 'EXPERT_WITNESS',
}
