// Auto-generated types for api_tokens table
// DO NOT EDIT - Generated by chittyschema


/**
 * api_tokens table
 * Owner: chittyauth
 * ChittyAuth: API authentication tokens for service access
 */
export interface ApiTokens {
  id?: string;
  identity_id?: string;
  token_hash: string;
  name: string;
  scopes?: string[];
  status?: string;
  last_used_at?: Date | string;
  expires_at?: Date | string;
  created_at?: Date | string;
  /** Token type: bearer (JWT) or certificate (mTLS) */
  type?: string;
  /** PEM-encoded X.509 certificate for mTLS authentication */
  certificate_pem?: string;
  /** Certificate serial number for revocation checking */
  certificate_serial?: string;
  /** SHA-256 fingerprint of the certificate */
  certificate_fingerprint?: string;
}

/**
 * Insert type for api_tokens (excludes auto-generated fields)
 */
export type ApiTokensInsert = Omit<ApiTokens, 
  'id' | 'created_at'
>;

/**
 * Update type for api_tokens (all fields optional except id)
 */
export type ApiTokensUpdate = Partial<ApiTokens> & Pick<ApiTokens, 'id'>;
