// Auto-generated types for credentials table
// DO NOT EDIT - Generated by chittyschema


/**
 * credentials table
 * Owner: chittyid
 * ChittyID: Digital credentials issued to identities
 */
export interface Credentials {
  id?: string;
  identity_id: string;
  type: string;
  issuer_did: string;
  credential_data: Record<string, any>;
  qr_code?: string;
  nfc_data?: string;
  status?: string;
  issued_at?: Date | string;
  expires_at?: Date | string;
  created_at?: Date | string;
}

/**
 * Insert type for credentials (excludes auto-generated fields)
 */
export type CredentialsInsert = Omit<Credentials, 
  'id' | 'issued_at' | 'created_at'
>;

/**
 * Update type for credentials (all fields optional except id)
 */
export type CredentialsUpdate = Partial<Credentials> & Pick<Credentials, 'id'>;
