// Auto-generated types for reception_sessions table
// DO NOT EDIT - Generated by chittyschema


/**
 * reception_sessions table
 * Owner: chittyreception
 */
export interface ReceptionSessions {
  id?: string;
  identity_id: string;
  phone_number: string;
  status?: string;
  context?: Record<string, any>;
  ai_summary?: string;
  last_interaction_at?: Date | string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for reception_sessions (excludes auto-generated fields)
 */
export type ReceptionSessionsInsert = Omit<ReceptionSessions, 
  'id' | 'last_interaction_at' | 'created_at' | 'updated_at'
>;

/**
 * Update type for reception_sessions (all fields optional except id)
 */
export type ReceptionSessionsUpdate = Partial<ReceptionSessions> & Pick<ReceptionSessions, 'id'>;
