// Auto-generated types for service_registrations table
// DO NOT EDIT - Generated by chittyschema


/**
 * service_registrations table
 * Owner: unknown
 * ChittyRegister - Service registrations in ChittyOS ecosystem. Owned by ChittyRegister service.
 */
export interface ServiceRegistrations {
  /** ChittyID in format VV-G-LLL-SSSS-T-YM-C-X. Generated by ChittyID service for entity type SERVICE. */
  chitty_id: string;
  service_name: string;
  description: string;
  version: string;
  /** Array of endpoint paths. Schema: ["/health", "/api/v1/status", ...]. Must include /health and /api/v1/status. */
  endpoints: Record<string, any>;
  /** Service schema definition. Schema: {"version": "1.0", "entities": ["PERSON", "TOOL"], "compliance": {...}}. */
  schema: Record<string, any>;
  /** Security configuration. Schema: {"authentication": "jwt|oauth2|apikey", "encryption": "tls|https", "scope": [...]}. */
  security: Record<string, any>;
  status?: string;
  registered_at?: Date | string;
  revoked_at?: Date | string;
  revocation_reason?: string;
  deleted_at?: Date | string;
  deletion_reason?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  /** Optional public base URL for the service. */
  base_url?: string | null;
  /**
   * Optional private-mesh endpoint descriptor. NULL for public-only services.
   * When set, must contain transport (discriminator), service, magic_dns, ports[].
   * Today only transport="tailscale" is supported, enforced by
   * service_registrations_private_endpoint_shape CHECK constraint.
   * See chittycanon://infrastructure/network/tailscale-services.
   */
  private_endpoint?: PrivateEndpoint | null;
}

/**
 * Private-mesh endpoint shape enforced by the
 * service_registrations_private_endpoint_shape CHECK constraint.
 */
export interface PrivateEndpoint {
  transport: 'tailscale';
  service: string;
  magic_dns: string;
  ports: number[];
  [key: string]: any;
}

/**
 * Insert type for service_registrations (excludes auto-generated fields)
 */
export type ServiceRegistrationsInsert = Omit<ServiceRegistrations, 
  'registered_at' | 'created_at' | 'updated_at'
>;

/**
 * Update type for service_registrations (all fields optional)
 */
export type ServiceRegistrationsUpdate = Partial<ServiceRegistrations>;
