// Auto-generated types for service_certifications table
// DO NOT EDIT - Generated by chittyschema


/**
 * service_certifications table
 * Owner: unknown
 * ChittyRegister - Compliance certificates issued to registered services via ChittyCert.
 */
export interface ServiceCertifications {
  chitty_id: string;
  registration_chitty_id: string;
  certificate_id: string;
  chitty_cert_id?: string;
  issued_at: Date | string;
  expires_at: Date | string;
  issuer?: string;
  certificate_type?: string;
  /** Cryptographic signature from ChittyCert (delegated CA from ChittyTrust root). */
  signature: string;
  status?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
}

/**
 * Insert type for service_certifications (excludes auto-generated fields)
 */
export type ServiceCertificationsInsert = Omit<ServiceCertifications, 
  'created_at'
>;

/**
 * Update type for service_certifications (all fields optional)
 */
export type ServiceCertificationsUpdate = Partial<ServiceCertifications>;
