// Auto-generated types for spatial_ref_sys table
// DO NOT EDIT - Generated by chittyschema


/**
 * spatial_ref_sys table
 * Owner: unknown
 */
export interface SpatialRefSys {
  srid: number;
  auth_name?: string;
  auth_srid?: number;
  srtext?: string;
  proj4text?: string;
}

/**
 * Insert type for spatial_ref_sys (excludes auto-generated fields)
 */
export type SpatialRefSysInsert = Omit<SpatialRefSys, 
  never
>;

/**
 * Update type for spatial_ref_sys (all fields optional)
 */
export type SpatialRefSysUpdate = Partial<SpatialRefSys>;
