// Auto-generated types for ai_messages table
// DO NOT EDIT - Generated by chittyschema

/**
 * ai_messages table
 * Owner: chittyfinance
 * ChittyFinance: AI financial advice conversation history (GPT-4o).
 */
export interface AiMessages {
  id?: string;
  tenant_id: string;
  user_id: string;
  content: string;
  role: 'system' | 'user' | 'assistant';
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
}

/**
 * Insert type for ai_messages (excludes auto-generated fields)
 */
export type AiMessagesInsert = Omit<AiMessages,
  'id' | 'created_at'
>;

/**
 * Update type for ai_messages (all fields optional except id)
 */
export type AiMessagesUpdate = Partial<AiMessages> & Pick<AiMessages, 'id'>;
