// Auto-generated types for chart_of_accounts table
// DO NOT EDIT - Generated by chittyschema

/**
 * chart_of_accounts table
 * Owner: chittyfinance
 * ChittyFinance: Database-backed COA with tenant customization. NULL tenant_id = global defaults.
 */
export interface ChartOfAccounts {
  id?: string;
  tenant_id?: string | null;
  code: string;
  name: string;
  type: 'asset' | 'liability' | 'equity' | 'income' | 'expense';
  subtype?: string | null;
  description?: string | null;
  schedule_e_line?: string | null;
  tax_deductible?: boolean;
  parent_code?: string | null;
  is_active?: boolean;
  effective_date?: Date | string | null;
  modified_by?: string | null;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for chart_of_accounts (excludes auto-generated fields)
 */
export type ChartOfAccountsInsert = Omit<ChartOfAccounts,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for chart_of_accounts (all fields optional except id)
 */
export type ChartOfAccountsUpdate = Partial<ChartOfAccounts> & Pick<ChartOfAccounts, 'id'>;
