// Auto-generated types for classification_audit table
// DO NOT EDIT - Generated by chittyschema

/**
 * classification_audit table
 * Owner: chittyfinance
 * ChittyFinance: Immutable audit trail for every COA classification change.
 * Enforces maker/checker: L2 classifies, L3 reconciles.
 */
export interface ClassificationAudit {
  id?: string;
  transaction_id: string;
  tenant_id: string;
  previous_coa_code?: string | null;
  new_coa_code: string;
  /** Action type: classify, reclassify, suggest, re-suggest, reconcile, override */
  action: 'classify' | 'reclassify' | 'suggest' | 're-suggest' | 'reconcile' | 'override';
  /** Trust level: L0 (ingest), L1 (suggest), L2 (classify), L3 (reconcile), L4 (govern) */
  trust_level: 'L0' | 'L1' | 'L2' | 'L3' | 'L4';
  /** User UUID, agent session ID, or 'auto' */
  actor_id: string;
  actor_type: 'user' | 'agent' | 'system';
  /** Confidence score 0.000-1.000 at time of action */
  confidence?: number | null;
  reason?: string | null;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
}

/**
 * Insert type for classification_audit (excludes auto-generated fields)
 */
export type ClassificationAuditInsert = Omit<ClassificationAudit,
  'id' | 'created_at'
>;

/**
 * Update type for classification_audit (all fields optional except id)
 */
export type ClassificationAuditUpdate = Partial<ClassificationAudit> & Pick<ClassificationAudit, 'id'>;
