// Auto-generated types for comms_log table
// DO NOT EDIT - Generated by chittyschema

/**
 * comms_log table
 * Owner: chittyfinance
 * ChittyFinance: Communication log for SMS/email sent to rental tenants. GDPR-sensitive.
 */
export interface CommsLog {
  id?: string;
  tenant_id: string;
  property_id?: string | null;
  recipient_name: string;
  recipient_contact: string;
  channel: 'sms' | 'email';
  template?: string | null;
  body: string;
  status?: string;
  sent_at?: Date | string;
  metadata?: Record<string, any> | null;
}

/**
 * Insert type for comms_log (excludes auto-generated fields)
 */
export type CommsLogInsert = Omit<CommsLog,
  'id'
>;

/**
 * Update type for comms_log (all fields optional except id)
 */
export type CommsLogUpdate = Partial<CommsLog> & Pick<CommsLog, 'id'>;
