// Auto-generated types for integrations table
// DO NOT EDIT - Generated by chittyschema

/**
 * integrations table
 * Owner: chittyfinance
 * ChittyFinance: Service integration connections (Mercury, Wave, Stripe). Credentials encrypted at rest.
 */
export interface Integrations {
  id?: string;
  tenant_id: string;
  service_type: string;
  name: string;
  description?: string | null;
  connected?: boolean;
  credentials?: Record<string, any> | null;
  last_synced?: Date | string | null;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for integrations (excludes auto-generated fields)
 */
export type IntegrationsInsert = Omit<Integrations,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for integrations (all fields optional except id)
 */
export type IntegrationsUpdate = Partial<Integrations> & Pick<Integrations, 'id'>;
