// Auto-generated types for properties table
// DO NOT EDIT - Generated by chittyschema

/**
 * properties table
 * Owner: chittyfinance
 * ChittyFinance: Real estate assets with multi-currency support. Tenant-scoped.
 */
export interface Properties {
  id?: string;
  tenant_id: string;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  country?: string;
  property_type: 'condo' | 'apartment' | 'house' | 'commercial';
  purchase_price?: number | null;
  purchase_currency?: string;
  purchase_date?: Date | string | null;
  current_value?: number | null;
  current_value_currency?: string;
  metadata?: Record<string, any> | null;
  is_active?: boolean;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for properties (excludes auto-generated fields)
 */
export type PropertiesInsert = Omit<Properties,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for properties (all fields optional except id)
 */
export type PropertiesUpdate = Partial<Properties> & Pick<Properties, 'id'>;
