// Auto-generated types for tenant_users table
// DO NOT EDIT - Generated by chittyschema

/**
 * tenant_users table
 * Owner: chittyfinance
 * ChittyFinance: User access to tenants with role-based permissions
 */
export interface TenantUsers {
  id?: string;
  tenant_id: string;
  user_id: string;
  role?: string;
  permissions?: Record<string, any> | null;
  created_at?: Date | string;
}

/**
 * Insert type for tenant_users (excludes auto-generated fields)
 */
export type TenantUsersInsert = Omit<TenantUsers,
  'id' | 'created_at'
>;

/**
 * Update type for tenant_users (all fields optional except id)
 */
export type TenantUsersUpdate = Partial<TenantUsers> & Pick<TenantUsers, 'id'>;
