// Auto-generated types for tenants table
// DO NOT EDIT - Generated by chittyschema

/**
 * tenants table
 * Owner: chittyfinance
 * ChittyFinance: Legal entities (LLCs, properties, management companies)
 */
export interface Tenants {
  id?: string;
  name: string;
  slug: string;
  type: 'holding' | 'series' | 'property' | 'management' | 'personal';
  parent_id?: string | null;
  tax_id?: string | null;
  metadata?: Record<string, any> | null;
  is_active?: boolean;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for tenants (excludes auto-generated fields)
 */
export type TenantsInsert = Omit<Tenants,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for tenants (all fields optional except id)
 */
export type TenantsUpdate = Partial<Tenants> & Pick<Tenants, 'id'>;
