// Auto-generated types for workflows table
// DO NOT EDIT - Generated by chittyschema

/**
 * workflows table
 * Owner: chittyfinance
 * ChittyFinance: Approval workflows for maintenance, expenses, and vendor dispatch.
 */
export interface Workflows {
  id?: string;
  tenant_id: string;
  property_id?: string | null;
  type: 'maintenance_request' | 'expense_approval' | 'vendor_dispatch';
  title: string;
  description?: string | null;
  requestor?: string | null;
  cost_estimate?: number | null;
  cost_currency?: string;
  status?: string;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for workflows (excludes auto-generated fields)
 */
export type WorkflowsInsert = Omit<Workflows,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for workflows (all fields optional except id)
 */
export type WorkflowsUpdate = Partial<Workflows> & Pick<Workflows, 'id'>;
