// Auto-generated types for accounts table
// DO NOT EDIT - Generated by chittyschema

/**
 * accounts table
 * Owner: chittyfinance
 * ChittyFinance: Financial accounts (bank, credit, investment, liability). Tenant-scoped.
 */
export interface Accounts {
  id?: string;
  tenant_id: string;
  name: string;
  type: string;
  institution?: string | null;
  account_number?: string | null;
  balance?: number;
  currency?: string;
  external_id?: string | null;
  is_active?: boolean;
  metadata?: Record<string, any> | null;
  liability_details?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for accounts (excludes auto-generated fields)
 */
export type AccountsInsert = Omit<Accounts,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for accounts (all fields optional except id)
 */
export type AccountsUpdate = Partial<Accounts> & Pick<Accounts, 'id'>;
