// Auto-generated types for allocation_rules table
// DO NOT EDIT - Generated by chittyschema

/**
 * allocation_rules table
 * Owner: chittyfinance
 * ChittyFinance: Automated inter-company allocation rules.
 */
export interface AllocationRules {
  id?: string;
  name: string;
  description?: string | null;
  rule_type: 'management_fee' | 'cost_sharing' | 'rent_passthrough' | 'custom_pct';
  source_tenant_id: string;
  target_tenant_id: string;
  percentage?: number | null;
  fixed_amount?: number | null;
  frequency?: string;
  source_category?: string | null;
  allocation_method?: string;
  is_active?: boolean;
  metadata?: Record<string, any> | null;
  last_run_at?: Date | string | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for allocation_rules (excludes auto-generated fields)
 */
export type AllocationRulesInsert = Omit<AllocationRules,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for allocation_rules (all fields optional except id)
 */
export type AllocationRulesUpdate = Partial<AllocationRules> & Pick<AllocationRules, 'id'>;
