// Auto-generated types for allocation_runs table
// DO NOT EDIT - Generated by chittyschema

/**
 * allocation_runs table
 * Owner: chittyfinance
 * ChittyFinance: Audit trail for allocation rule executions.
 */
export interface AllocationRuns {
  id?: string;
  rule_id: string;
  period_start: Date | string;
  period_end: Date | string;
  source_amount: number;
  allocated_amount: number;
  transaction_count?: number;
  intercompany_transaction_id?: string | null;
  status?: string;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
}

/**
 * Insert type for allocation_runs (excludes auto-generated fields)
 */
export type AllocationRunsInsert = Omit<AllocationRuns,
  'id' | 'created_at'
>;

/**
 * Update type for allocation_runs (all fields optional except id)
 */
export type AllocationRunsUpdate = Partial<AllocationRuns> & Pick<AllocationRuns, 'id'>;
