// Auto-generated types for intercompany_transactions table
// DO NOT EDIT - Generated by chittyschema

/**
 * intercompany_transactions table
 * Owner: chittyfinance
 * ChittyFinance: Inter-company transfers between tenants with multi-currency support.
 */
export interface IntercompanyTransactions {
  id?: string;
  from_tenant_id: string;
  to_tenant_id: string;
  amount: number;
  currency?: string;
  /** Multiply: amount * exchangeRate = USD equivalent */
  exchange_rate?: number | null;
  description: string;
  date: Date | string;
  from_transaction_id?: string | null;
  to_transaction_id?: string | null;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
}

/**
 * Insert type for intercompany_transactions (excludes auto-generated fields)
 */
export type IntercompanyTransactionsInsert = Omit<IntercompanyTransactions,
  'id' | 'created_at'
>;

/**
 * Update type for intercompany_transactions (all fields optional except id)
 */
export type IntercompanyTransactionsUpdate = Partial<IntercompanyTransactions> & Pick<IntercompanyTransactions, 'id'>;
