// Auto-generated types for leases table
// DO NOT EDIT - Generated by chittyschema

/**
 * leases table
 * Owner: chittyfinance
 * ChittyFinance: Rental leases for units. GDPR-sensitive (tenant PII).
 */
export interface Leases {
  id?: string;
  unit_id: string;
  /** Rental tenant (person name), not system tenant entity */
  tenant_name: string;
  tenant_email?: string | null;
  tenant_phone?: string | null;
  start_date: Date | string;
  end_date: Date | string;
  monthly_rent: number;
  currency?: string;
  security_deposit?: number | null;
  status?: 'active' | 'expired' | 'terminated';
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for leases (excludes auto-generated fields)
 */
export type LeasesInsert = Omit<Leases,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for leases (all fields optional except id)
 */
export type LeasesUpdate = Partial<Leases> & Pick<Leases, 'id'>;
