// Auto-generated types for property_valuations table
// DO NOT EDIT - Generated by chittyschema

/**
 * property_valuations table
 * Owner: chittyfinance
 * ChittyFinance: Cached AVM estimates from external providers (Zillow, Redfin, HouseCanary, ATTOM, County).
 */
export interface PropertyValuations {
  id?: string;
  property_id: string;
  tenant_id: string;
  source: 'zillow' | 'redfin' | 'housecanary' | 'attom' | 'county' | 'manual';
  estimate?: number | null;
  low?: number | null;
  high?: number | null;
  rental_estimate?: number | null;
  /** Provider confidence score 0.000-1.000 */
  confidence?: number | null;
  details?: Record<string, any> | null;
  fetched_at?: Date | string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for property_valuations (excludes auto-generated fields)
 */
export type PropertyValuationsInsert = Omit<PropertyValuations,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for property_valuations (all fields optional except id)
 */
export type PropertyValuationsUpdate = Partial<PropertyValuations> & Pick<PropertyValuations, 'id'>;
