// Auto-generated types for tasks table
// DO NOT EDIT - Generated by chittyschema

/**
 * tasks table
 * Owner: chittyfinance
 * ChittyFinance: Financial tasks with priority and status tracking. Tenant-scoped.
 */
export interface Tasks {
  id?: string;
  tenant_id: string;
  user_id?: string | null;
  title: string;
  description?: string | null;
  due_date?: Date | string | null;
  priority?: 'urgent' | 'high' | 'medium' | 'low' | null;
  status?: string;
  related_to?: string | null;
  related_id?: string | null;
  completed?: boolean;
  completed_at?: Date | string | null;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for tasks (excludes auto-generated fields)
 */
export type TasksInsert = Omit<Tasks,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for tasks (all fields optional except id)
 */
export type TasksUpdate = Partial<Tasks> & Pick<Tasks, 'id'>;
