// Auto-generated types for transactions table
// DO NOT EDIT - Generated by chittyschema

/**
 * transactions table
 * Owner: chittyfinance
 * ChittyFinance: Financial transactions with trust-path COA classification (L0-L4). Tenant-scoped.
 */
export interface Transactions {
  id?: string;
  tenant_id: string;
  account_id: string;
  amount: number;
  currency?: string;
  type: 'income' | 'expense' | 'transfer';
  category?: string | null;
  description: string;
  date: Date | string;
  payee?: string | null;
  property_id?: string | null;
  unit_id?: string | null;
  external_id?: string | null;
  /** Authoritative COA classification (L2+ can write) */
  coa_code?: string | null;
  /** AI/keyword proposal (L1 writes, L3 reviews) */
  suggested_coa_code?: string | null;
  /** Confidence score 0.000-1.000 */
  classification_confidence?: number | null;
  /** Who/what set coa_code: user UUID, agent session ID, or 'auto' */
  classified_by?: string | null;
  classified_at?: Date | string | null;
  reconciled?: boolean;
  /** L3 auditor who locked this transaction */
  reconciled_by?: string | null;
  reconciled_at?: Date | string | null;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for transactions (excludes auto-generated fields)
 */
export type TransactionsInsert = Omit<Transactions,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for transactions (all fields optional except id)
 */
export type TransactionsUpdate = Partial<Transactions> & Pick<Transactions, 'id'>;
