// Auto-generated types for units table
// DO NOT EDIT - Generated by chittyschema

/**
 * units table
 * Owner: chittyfinance
 * ChittyFinance: Rental units within properties.
 */
export interface Units {
  id?: string;
  property_id: string;
  unit_number?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  square_feet?: number | null;
  monthly_rent?: number | null;
  rent_currency?: string;
  is_active?: boolean;
  metadata?: Record<string, any> | null;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for units (excludes auto-generated fields)
 */
export type UnitsInsert = Omit<Units,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for units (all fields optional except id)
 */
export type UnitsUpdate = Partial<Units> & Pick<Units, 'id'>;
