// Auto-generated types for users table
// DO NOT EDIT - Generated by chittyschema

/**
 * users table
 * Owner: chittyfinance
 * ChittyFinance: User accounts with optional ChittyID SSO binding
 */
export interface Users {
  id?: string;
  chitty_id?: string | null;
  email: string;
  password_hash?: string | null;
  name: string;
  role?: string;
  is_active?: boolean;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for users (excludes auto-generated fields)
 */
export type UsersInsert = Omit<Users,
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for users (all fields optional except id)
 */
export type UsersUpdate = Partial<Users> & Pick<Users, 'id'>;
