// Auto-generated types for api_usage_ledger table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * api_usage_ledger table
 * Owner: chittyledger
 * ChittyLedger: API usage tracking for rate limiting and analytics
 */
export interface ApiUsageLedger {
  id?: string;
  request_id: string;
  user_id?: string;
  api_key_hash?: string;
  endpoint: string;
  method: string;
  status_code?: number;
  response_time_ms?: number;
  request_size_bytes?: number;
  response_size_bytes?: number;
  ip_address?: string;
  user_agent?: string;
  referer?: string;
  error_message?: string;
  metadata?: Record<string, any>;
  timestamp?: Date | string;
}

/**
 * Insert type for api_usage_ledger (excludes auto-generated fields)
 */
export type ApiUsageLedgerInsert = Omit<ApiUsageLedger, 
  'id' | 'timestamp'
>;

/**
 * Update type for api_usage_ledger (all fields optional except id)
 */
export type ApiUsageLedgerUpdate = Partial<ApiUsageLedger> & Pick<ApiUsageLedger, 'id'>;
