// Auto-generated types for blockchain_records table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * blockchain_records table
 * Owner: chittychain
 * ChittyLedger: Blockchain transaction records and cryptographic proofs
 */
export interface BlockchainRecords {
  id?: string;
  record_id: string;
  blockchain_network: BlockchainNetwork;
  transaction_hash: string;
  block_number?: number;
  block_timestamp?: Date | string;
  contract_address?: string;
  from_address: string;
  to_address?: string;
  gas_used?: number;
  gas_price?: number;
  entity_type: string;
  entity_id: string;
  metadata_uri?: string;
  metadata_hash?: string;
  proof_data?: Record<string, any>;
  minted_by?: string;
  created_at?: Date | string;
}

/**
 * Insert type for blockchain_records (excludes auto-generated fields)
 */
export type BlockchainRecordsInsert = Omit<BlockchainRecords, 
  'id' | 'created_at'
>;

/**
 * Update type for blockchain_records (all fields optional except id)
 */
export type BlockchainRecordsUpdate = Partial<BlockchainRecords> & Pick<BlockchainRecords, 'id'>;
