// Auto-generated types for cases table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * cases table
 * Owner: chittyledger
 * ChittyLedger: Legal cases and court proceedings
 */
export interface Cases {
  id?: string;
  chitty_id: string;
  docket_number: string;
  title: string;
  case_type: string;
  sub_type?: string;
  jurisdiction_id?: string;
  venue_id?: string;
  judge_name?: string;
  courtroom?: string;
  lead_counsel_id?: string;
  opposing_counsel_id?: string;
  filing_date?: Date | string;
  answer_due_date?: Date | string;
  discovery_deadline?: Date | string;
  motion_deadline?: Date | string;
  trial_date?: Date | string;
  status_conference_date?: Date | string;
  estimated_value?: number;
  actual_settlement?: number;
  attorney_fees?: number;
  court_costs?: number;
  status?: string;
  resolution_type?: string;
  resolution_date?: Date | string;
  is_confidential?: boolean;
  confidentiality_level?: string;
  sealed_portions?: Record<string, any>;
  parent_case_id?: string;
  related_case_ids?: string[];
  governing_law_ids?: string[];
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for cases (excludes auto-generated fields)
 */
export type CasesInsert = Omit<Cases, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for cases (all fields optional except id)
 */
export type CasesUpdate = Partial<Cases> & Pick<Cases, 'id'>;
