// Auto-generated types for case_parties table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * case_parties table
 * Owner: unknown
 */
export interface CaseParties {
  id?: string;
  case_id: string;
  person_id: string;
  role: string;
  party_number?: number;
  status?: string;
  service_address_id?: string;
  service_method?: string;
  served_date?: Date | string;
  served_by?: string;
  counsel_id?: string;
  pro_se?: boolean;
  added_date?: Date | string;
  removed_date?: Date | string;
  notes?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
}

/**
 * Insert type for case_parties (excludes auto-generated fields)
 */
export type CasePartiesInsert = Omit<CaseParties, 
  'id' | 'created_at'
>;

/**
 * Update type for case_parties (all fields optional except id)
 */
export type CasePartiesUpdate = Partial<CaseParties> & Pick<CaseParties, 'id'>;
