// Auto-generated types for chain_of_custody table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * chain_of_custody table
 * Owner: chittyledger
 * ChittyLedger: Immutable audit trail for evidence handling
 */
export interface ChainOfCustody {
  id?: string;
  evidence_id: string;
  action: string;
  performed_by: string;
  ip_address?: string;
  user_agent?: string;
  notes?: string;
  metadata?: Record<string, any>;
  timestamp?: Date | string;
}

/**
 * Insert type for chain_of_custody (excludes auto-generated fields)
 */
export type ChainOfCustodyInsert = Omit<ChainOfCustody, 
  'id' | 'timestamp'
>;

/**
 * Update type for chain_of_custody (all fields optional except id)
 */
export type ChainOfCustodyUpdate = Partial<ChainOfCustody> & Pick<ChainOfCustody, 'id'>;
