// Auto-generated types for contradictions table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * contradictions table
 * Owner: chittyledger
 * ChittyLedger: Detected contradictions between atomic facts
 */
export interface Contradictions {
  id?: string;
  fact_a_id: string;
  fact_b_id: string;
  contradiction_type: string;
  severity: string;
  explanation?: string;
  detected_by?: string;
  detected_at?: Date | string;
  resolved?: boolean;
  resolution_notes?: string;
}

/**
 * Insert type for contradictions (excludes auto-generated fields)
 */
export type ContradictionsInsert = Omit<Contradictions, 
  'id' | 'detected_at'
>;

/**
 * Update type for contradictions (all fields optional except id)
 */
export type ContradictionsUpdate = Partial<Contradictions> & Pick<Contradictions, 'id'>;
