// Auto-generated types for event_ledger table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * event_ledger table
 * Owner: chittyledger
 * ChittyLedger: Immutable event log for all ChittyOS services
 */
export interface EventLedger {
  id?: string;
  event_id: string;
  event_type: EventType;
  event_severity?: EventSeverity;
  service_name: string;
  user_id?: string;
  case_id?: string;
  action: string;
  entity_type?: string;
  entity_id?: string;
  ip_address?: string;
  user_agent?: string;
  request_id?: string;
  session_id?: string;
  metadata?: Record<string, any>;
  timestamp?: Date | string;
}

/**
 * Insert type for event_ledger (excludes auto-generated fields)
 */
export type EventLedgerInsert = Omit<EventLedger, 
  'id' | 'timestamp'
>;

/**
 * Update type for event_ledger (all fields optional except id)
 */
export type EventLedgerUpdate = Partial<EventLedger> & Pick<EventLedger, 'id'>;
