// Auto-generated types for event_store table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * event_store table
 * Owner: unknown
 */
export interface EventStore {
  id?: string;
  chitty_id: string;
  aggregate_id: string;
  aggregate_type: string;
  event_type: string;
  event_data: Record<string, any>;
  event_version: number;
  correlation_id?: string;
  causation_id?: string;
  user_id?: string;
  ip_address?: string;
  user_agent?: string;
  timestamp?: Date | string;
  metadata?: Record<string, any>;
  event_hash: string;
  previous_hash?: string;
}

/**
 * Insert type for event_store (excludes auto-generated fields)
 */
export type EventStoreInsert = Omit<EventStore, 
  'id' | 'timestamp'
>;

/**
 * Update type for event_store (all fields optional except id)
 */
export type EventStoreUpdate = Partial<EventStore> & Pick<EventStore, 'id'>;
