// Auto-generated types for gdpr_data_subjects table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * gdpr_data_subjects table
 * Owner: unknown
 */
export interface GdprDataSubjects {
  id?: string;
  person_id?: string;
  external_identifier?: string;
  lawful_basis: string;
  lawful_basis_details?: string;
  consent_status?: string;
  consent_date?: Date | string;
  consent_method?: string;
  consent_evidence?: Record<string, any>;
  right_to_access_requested?: boolean;
  right_to_rectification_requested?: boolean;
  right_to_erasure_requested?: boolean;
  right_to_portability_requested?: boolean;
  right_to_object_requested?: boolean;
  data_categories?: string[];
  processing_purposes?: string[];
  data_retention_period?: string;
  data_sources?: string[];
  third_party_recipients?: string[];
  international_transfers?: boolean;
  transfer_safeguards?: string;
  erasure_completed?: boolean;
  erasure_completed_at?: Date | string;
  rectification_completed?: boolean;
  rectification_completed_at?: Date | string;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for gdpr_data_subjects (excludes auto-generated fields)
 */
export type GdprDataSubjectsInsert = Omit<GdprDataSubjects, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for gdpr_data_subjects (all fields optional except id)
 */
export type GdprDataSubjectsUpdate = Partial<GdprDataSubjects> & Pick<GdprDataSubjects, 'id'>;
