// Auto-generated types for identity_phones table
// DO NOT EDIT - Generated by chittyschema


/**
 * identity_phones table
 * Owner: unknown
 */
export interface IdentityPhones {
  id?: string;
  identity_id: string;
  phone_number: string;
  verified?: boolean;
  verified_at?: Date | string;
  primary_phone?: boolean;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for identity_phones (excludes auto-generated fields)
 */
export type IdentityPhonesInsert = Omit<IdentityPhones, 
  'id'
>;

/**
 * Update type for identity_phones (all fields optional except id)
 */
export type IdentityPhonesUpdate = Partial<IdentityPhones> & Pick<IdentityPhones, 'id'>;
