// Auto-generated types for identities table
// DO NOT EDIT - Generated by chittyschema


/**
 * identities table
 * Owner: chittyid
 * ChittyID: Core identity records with DID and biometric data
 */
export interface Identities {
  id?: string;
  did: string;
  biometric_hash: string;
  public_key: string;
  metadata?: Record<string, any>;
  status?: string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for identities (excludes auto-generated fields)
 */
export type IdentitiesInsert = Omit<Identities, 
  'id'
>;

/**
 * Update type for identities (all fields optional except id)
 */
export type IdentitiesUpdate = Partial<Identities> & Pick<Identities, 'id'>;
