// Auto-generated types for import_audit_log table
// DO NOT EDIT - Generated by chittyschema


/**
 * import_audit_log table
 * Owner: unknown
 */
export interface ImportAuditLog {
  id?: string;
  file_id: string;
  filename?: string;
  stage: string;
  status: string;
  details?: Record<string, any>;
  error_message?: string;
  imported_to?: string[];
  chronicle_event_id?: string;
  created_at?: Date | string;
}

/**
 * Insert type for import_audit_log (excludes auto-generated fields)
 */
export type ImportAuditLogInsert = Omit<ImportAuditLog, 
  never
>;

/**
 * Update type for import_audit_log (all fields optional except id)
 */
export type ImportAuditLogUpdate = Partial<ImportAuditLog> & Pick<ImportAuditLog, 'id'>;
