// Auto-generated types for invoices table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * invoices table
 * Owner: chittyledger
 * ChittyLedger: Invoice records for billing
 */
export interface Invoices {
  id?: string;
  invoice_number: string;
  user_id: string;
  case_id?: string;
  amount: number;
  currency?: string;
  status?: string;
  due_date?: Date | string;
  paid_date?: Date | string;
  line_items: Record<string, any>;
  notes?: string;
  payment_link?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for invoices (excludes auto-generated fields)
 */
export type InvoicesInsert = Omit<Invoices, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for invoices (all fields optional except id)
 */
export type InvoicesUpdate = Partial<Invoices> & Pick<Invoices, 'id'>;
