// Auto-generated types for oauth_authorization_codes table
// DO NOT EDIT - Generated by chittyschema


/**
 * oauth_authorization_codes table
 * Owner: chittyauth
 * ChittyAuth: Temporary OAuth authorization codes for OAuth flow
 */
export interface OauthAuthorizationCodes {
  id?: string;
  code: string;
  client_id: string;
  redirect_uri: string;
  scope: string;
  identity_did?: string;
  code_challenge?: string;
  expires_at: Date | string;
  created_at?: Date | string;
}

/**
 * Insert type for oauth_authorization_codes (excludes auto-generated fields)
 */
export type OauthAuthorizationCodesInsert = Omit<OauthAuthorizationCodes, 
  'id'
>;

/**
 * Update type for oauth_authorization_codes (all fields optional except id)
 */
export type OauthAuthorizationCodesUpdate = Partial<OauthAuthorizationCodes> & Pick<OauthAuthorizationCodes, 'id'>;
