// Auto-generated types for people table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * people table
 * Owner: unknown
 */
export interface People {
  id?: string;
  chitty_id: string;
  first_name?: string;
  middle_name?: string;
  last_name?: string;
  legal_name: string;
  aliases?: string[];
  entity_type: string;
  sub_type?: string;
  ssn?: string;
  ein?: string;
  foreign_id?: string;
  date_of_birth?: Date | string;
  date_of_incorporation?: Date | string;
  date_of_dissolution?: Date | string;
  place_of_birth_id?: string;
  incorporation_place_id?: string;
  primary_address_id?: string;
  parent_entity_id?: string;
  status?: string;
  verification_status?: string;
  verification_method?: string;
  verified_at?: Date | string;
  verified_by?: string;
  gdpr_lawful_basis?: string;
  gdpr_consent_status?: string;
  gdpr_deleted?: boolean;
  gdpr_deleted_at?: Date | string;
  retention_period?: string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  version_number?: number;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for people (excludes auto-generated fields)
 */
export type PeopleInsert = Omit<People, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for people (all fields optional except id)
 */
export type PeopleUpdate = Partial<People> & Pick<People, 'id'>;
