// Auto-generated types for quarantine_queue table
// DO NOT EDIT - Generated by chittyschema


/**
 * quarantine_queue table
 * Owner: unknown
 */
export interface QuarantineQueue {
  id?: string;
  source: string;
  source_file_id: string;
  source_path?: string;
  filename: string;
  filesize?: number;
  mime_type?: string;
  content?: string;
  quality_result: Record<string, any>;
  confidence?: number;
  issues?: Record<string, any>;
  status?: string;
  reviewed_by?: string;
  reviewed_at?: Date | string;
  reviewer_notes?: string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for quarantine_queue (excludes auto-generated fields)
 */
export type QuarantineQueueInsert = Omit<QuarantineQueue, 
  never
>;

/**
 * Update type for quarantine_queue (all fields optional except id)
 */
export type QuarantineQueueUpdate = Partial<QuarantineQueue> & Pick<QuarantineQueue, 'id'>;
