// Auto-generated types for reception_calls table
// DO NOT EDIT - Generated by chittyschema


/**
 * reception_calls table
 * Owner: unknown
 */
export interface ReceptionCalls {
  id?: string;
  identity_id: string;
  call_id: string;
  direction: string;
  from_number: string;
  to_number: string;
  status?: string;
  duration_seconds?: number;
  recording_url?: string;
  transcription?: string;
  metadata?: Record<string, any>;
  started_at?: Date | string;
  answered_at?: Date | string;
  ended_at?: Date | string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for reception_calls (excludes auto-generated fields)
 */
export type ReceptionCallsInsert = Omit<ReceptionCalls, 
  'id'
>;

/**
 * Update type for reception_calls (all fields optional except id)
 */
export type ReceptionCallsUpdate = Partial<ReceptionCalls> & Pick<ReceptionCalls, 'id'>;
