// Auto-generated types for registrations table
// DO NOT EDIT - Generated by chittyschema


/**
 * registrations table
 * Owner: chittyauth
 * ChittyAuth: User registration records linking ChittyIDs to emails
 */
export interface Registrations {
  id?: string;
  chitty_id: string;
  email: string;
  name: string;
  registered_at: number;
  verified_at?: number;
  verification_method?: string;
  created_at?: Date | string;
}

/**
 * Insert type for registrations (excludes auto-generated fields)
 */
export type RegistrationsInsert = Omit<Registrations, 
  'id'
>;

/**
 * Update type for registrations (all fields optional except id)
 */
export type RegistrationsUpdate = Partial<Registrations> & Pick<Registrations, 'id'>;
