// Auto-generated types for schema_versions table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * schema_versions table
 * Owner: unknown
 */
export interface SchemaVersions {
  version: string;
  applied_at?: Date | string;
  migration_script?: string;
  rollback_script?: string;
  description?: string;
}

/**
 * Insert type for schema_versions (excludes auto-generated fields)
 */
export type SchemaVersionsInsert = Omit<SchemaVersions, 
  'applied_at'
>;

/**
 * Update type for schema_versions (all fields optional)
 */
export type SchemaVersionsUpdate = Partial<SchemaVersions>;
