// Auto-generated types for subscriptions table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * subscriptions table
 * Owner: chittyledger
 * ChittyLedger: Subscription lifecycle tracking
 */
export interface Subscriptions {
  id?: string;
  subscription_id: string;
  user_id: string;
  plan_name: string;
  plan_price: number;
  billing_cycle: string;
  status?: SubscriptionStatus;
  stripe_subscription_id?: string;
  current_period_start: Date | string;
  current_period_end: Date | string;
  cancel_at_period_end?: boolean;
  cancelled_at?: Date | string;
  trial_start?: Date | string;
  trial_end?: Date | string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for subscriptions (excludes auto-generated fields)
 */
export type SubscriptionsInsert = Omit<Subscriptions, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for subscriptions (all fields optional except id)
 */
export type SubscriptionsUpdate = Partial<Subscriptions> & Pick<Subscriptions, 'id'>;
