// Auto-generated types for things table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * things table
 * Owner: unknown
 */
export interface Things {
  id?: string;
  chitty_id: string;
  name: string;
  description?: string;
  thing_type: string;
  sub_type?: string;
  serial_number?: string;
  model_number?: string;
  manufacturer?: string;
  year_manufactured?: number;
  physical_condition?: string;
  current_owner_id?: string;
  ownership_type?: string;
  ownership_percentage?: number;
  current_value?: number;
  currency?: string;
  valuation_date?: Date | string;
  valuation_method?: string;
  acquisition_date?: Date | string;
  acquisition_cost?: number;
  current_location_id?: string;
  file_hash?: string;
  file_size?: number;
  mime_type?: string;
  media_url?: string;
  account_number?: string;
  routing_number?: string;
  institution_name?: string;
  institution_id?: string;
  chain_of_custody_required?: boolean;
  is_confidential?: boolean;
  confidentiality_level?: string;
  status?: string;
  verification_status?: string;
  verified_at?: Date | string;
  verified_by?: string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  version_number?: number;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for things (excludes auto-generated fields)
 */
export type ThingsInsert = Omit<Things, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for things (all fields optional except id)
 */
export type ThingsUpdate = Partial<Things> & Pick<Things, 'id'>;
