// Auto-generated types for users table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * users table
 * Owner: chittyledger
 * ChittyLedger: Legal case participants and system users
 */
export interface Users {
  id?: string;
  chitty_id: string;
  email: string;
  password_hash?: string;
  two_fa_secret?: string;
  two_fa_enabled?: boolean;
  role: string;
  permissions?: string[];
  bar_number?: string;
  license_state?: string;
  license_expiration?: Date | string;
  last_login?: Date | string;
  login_count?: number;
  failed_login_attempts?: number;
  account_locked?: boolean;
  account_locked_until?: Date | string;
  linked_person_id?: string;
  trust_score?: number;
  verified?: boolean;
  verified_at?: Date | string;
  verified_by?: string;
  current_session_id?: string;
  session_data?: Record<string, any>;
  preferences?: Record<string, any>;
  status?: string;
  gdpr_deleted?: boolean;
  gdpr_deleted_at?: Date | string;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for users (excludes auto-generated fields)
 */
export type UsersInsert = Omit<Users, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for users (all fields optional except id)
 */
export type UsersUpdate = Partial<Users> & Pick<Users, 'id'>;
