// Auto-generated types for verification_tasks table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * verification_tasks table
 * Owner: unknown
 */
export interface VerificationTasks {
  id?: string;
  chitty_id: string;
  task_type: string;
  task_subtype?: string;
  description?: string;
  subject_type: string;
  subject_id: string;
  assigned_to?: string;
  assigned_by?: string;
  priority?: string;
  status?: string;
  workflow_stage?: string;
  due_date?: Date | string;
  started_at?: Date | string;
  completed_at?: Date | string;
  estimated_hours?: number;
  actual_hours?: number;
  verification_method?: string;
  required_authorities?: string[];
  required_evidence?: string[];
  verification_criteria?: Record<string, any>;
  result?: string;
  result_confidence?: number;
  result_details?: Record<string, any>;
  findings?: string;
  recommendations?: string;
  reviewed_by?: string;
  reviewed_at?: Date | string;
  approved_by?: string;
  approved_at?: Date | string;
  follow_up_required?: boolean;
  follow_up_tasks?: string[];
  escalation_reason?: string;
  notes?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for verification_tasks (excludes auto-generated fields)
 */
export type VerificationTasksInsert = Omit<VerificationTasks, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for verification_tasks (all fields optional except id)
 */
export type VerificationTasksUpdate = Partial<VerificationTasks> & Pick<VerificationTasks, 'id'>;
