/**
 * Code Generators
 * Generate Pydantic, TypeScript, and Zod from table metadata
 */

interface TableMetadata {
  database: string;
  owner: string;
  columns: any[];
  description: string;
}

/**
 * Generate Pydantic model for Python
 */
export function generatePydanticModel(tableName: string, metadata: TableMetadata): string {
  const className = tableName
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  // For trust_scores, generate the full 6D model
  if (tableName === 'trust_scores') {
    return `"""
Auto-generated Pydantic model for trust_scores table
Generated by ChittySchema API at schema.chitty.cc
DO NOT EDIT - Regenerate when schema changes
"""

from datetime import datetime
from typing import Optional, Any
from uuid import UUID
from pydantic import BaseModel, Field


class TrustScores(BaseModel):
    """
    ${metadata.description}
    Database: ${metadata.database}
    Owner: ${metadata.owner}
    """
    id: Optional[UUID] = None
    identity_id: UUID

    # 6 Dimension Scores (0-100 scale)
    source_dimension: float = Field(ge=0, le=100, description="15% weight - Identity verification and credentials")
    temporal_dimension: float = Field(ge=0, le=100, description="10% weight - Historical consistency and longevity")
    channel_dimension: float = Field(ge=0, le=100, description="15% weight - Communication channel reliability")
    outcome_dimension: float = Field(ge=0, le=100, description="20% weight - Track record of positive outcomes")
    network_dimension: float = Field(ge=0, le=100, description="15% weight - Quality of network connections")
    justice_dimension: float = Field(ge=0, le=100, description="25% weight - Alignment with justice principles")

    # 4 Output Scores (0-100 scale)
    people_score: float = Field(ge=0, le=100, description="Interpersonal trust assessment")
    legal_score: float = Field(ge=0, le=100, description="Legal system alignment")
    state_score: float = Field(ge=0, le=100, description="Institutional trust level")
    chitty_score: float = Field(ge=0, le=100, description="Overall ChittyOS trust rating")

    # Composite & Metadata
    composite_score: float = Field(ge=0, le=100, description="Weighted average of all dimensions")
    trust_level: str = Field(default="L0_ANONYMOUS", description="L0-L4 lifecycle stage")
    confidence: float = Field(ge=0, le=100, description="Confidence in score accuracy")
    ai_enhanced: bool = True
    insights: Optional[dict] = None
    calculation_details: Optional[dict] = None

    calculated_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True  # Pydantic v2
        json_schema_extra = {
            "example": {
                "identity_id": "550e8400-e29b-41d4-a716-446655440000",
                "source_dimension": 85.0,
                "temporal_dimension": 75.0,
                "channel_dimension": 80.0,
                "outcome_dimension": 90.0,
                "network_dimension": 85.0,
                "justice_dimension": 88.0,
                "people_score": 87.5,
                "legal_score": 85.0,
                "state_score": 83.0,
                "chitty_score": 85.5,
                "composite_score": 85.5,
                "trust_level": "L3_PROFESSIONAL",
                "confidence": 92.0,
                "ai_enhanced": True
            }
        }


class TrustScoresInsert(BaseModel):
    """Insert model for trust_scores (excludes auto-generated fields)"""
    identity_id: UUID
    source_dimension: float = Field(ge=0, le=100)
    temporal_dimension: float = Field(ge=0, le=100)
    channel_dimension: float = Field(ge=0, le=100)
    outcome_dimension: float = Field(ge=0, le=100)
    network_dimension: float = Field(ge=0, le=100)
    justice_dimension: float = Field(ge=0, le=100)
    people_score: float = Field(ge=0, le=100)
    legal_score: float = Field(ge=0, le=100)
    state_score: float = Field(ge=0, le=100)
    chitty_score: float = Field(ge=0, le=100)
    composite_score: float = Field(ge=0, le=100)
    trust_level: str = "L0_ANONYMOUS"
    confidence: float = Field(ge=0, le=100)
    ai_enhanced: bool = True
    insights: Optional[dict] = None
    calculation_details: Optional[dict] = None
`;
  }

  // For trust_events
  if (tableName === 'trust_events') {
    return `"""
Auto-generated Pydantic model for trust_events table
Generated by ChittySchema API at schema.chitty.cc
"""

from datetime import datetime
from typing import Optional, List
from uuid import UUID
from pydantic import BaseModel, Field


class TrustEvents(BaseModel):
    """
    ${metadata.description}
    Database: ${metadata.database}
    Owner: ${metadata.owner}
    """
    id: Optional[UUID] = None
    identity_id: UUID
    event_type: str = Field(description="transaction, verification, endorsement, dispute, etc.")
    event_timestamp: datetime
    channel: Optional[str] = Field(None, description="verified_api, blockchain, email, etc.")
    outcome: str = Field(default="pending", description="positive, negative, neutral, pending")
    impact_score: float = Field(default=1.0, ge=0, le=10, description="How much this event impacts trust")
    related_identities: List[UUID] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)
    metadata: Optional[dict] = None
    created_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class TrustEventsInsert(BaseModel):
    """Insert model for trust_events"""
    identity_id: UUID
    event_type: str
    event_timestamp: datetime
    channel: Optional[str] = None
    outcome: str = "pending"
    impact_score: float = 1.0
    related_identities: List[UUID] = []
    tags: List[str] = []
    metadata: Optional[dict] = None
`;
  }

  // Generic model for other tables
  // Try to materialize fields from metadata.columns when available
  const fields = Array.isArray(metadata.columns) && metadata.columns.length > 0
    ? metadata.columns
        .map((c) => `    ${c.name}: ${pyType(c.type)}${c.optional || c.nullable ? ' | None' : ''}`)
        .join('\n')
    : `    # TODO: Add fields based on actual schema introspection\n    id: Optional[UUID] = None\n    created_at: Optional[datetime] = None\n    updated_at: Optional[datetime] = None`;

  return `"""
Auto-generated Pydantic model for ${tableName} table
Generated by ChittySchema API at schema.chitty.cc
"""

from datetime import datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel


class ${className}(BaseModel):
    """
    ${metadata.description}
    Database: ${metadata.database}
    Owner: ${metadata.owner}
    """
${fields}

    class Config:
        from_attributes = True
`;
}

/**
 * Generate TypeScript types
 */
export function generateTypeScript(tableName: string, metadata: TableMetadata): string {
  const interfaceName = tableName
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  // Build fields from metadata.columns when available
  const fields = Array.isArray(metadata.columns) && metadata.columns.length > 0
    ? metadata.columns
        .map((c) => `  ${c.name}${c.optional ? '?' : ''}: ${tsType(c.type)}${c.nullable ? ' | null' : ''};`)
        .join('\n')
    : `  id?: string;\n  // TODO: Add fields from schema introspection\n  created_at?: Date | string;\n  updated_at?: Date | string;`;

  return `/**
 * Auto-generated TypeScript types for ${tableName} table
 * Generated by ChittySchema API at schema.chitty.cc
 * DO NOT EDIT
 */

/**
 * ${metadata.description}
 * Database: ${metadata.database}
 * Owner: ${metadata.owner}
 */
export interface ${interfaceName} {
${fields}
}

export type ${interfaceName}Insert = Omit<${interfaceName}, 'id'>;
export type ${interfaceName}Update = Partial<${interfaceName}> & Pick<${interfaceName}, 'id'>;
`;
}

/**
 * Generate Zod validation schema
 */
export function generateZodSchema(tableName: string, metadata: TableMetadata): string {
  const schemaName = tableName
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  // Build Zod object from metadata.columns when available
  const shape = Array.isArray(metadata.columns) && metadata.columns.length > 0
    ? metadata.columns
        .map((c) => `  ${c.name}: ${zodType(c.type)}${c.nullable ? '.nullable()' : ''}${c.optional ? '.optional()' : ''}`)
        .join(',\n')
    : `  id: z.string().uuid().optional(),\n  // TODO: Add fields from schema introspection\n  created_at: z.coerce.date().optional(),\n  updated_at: z.coerce.date().optional()`;

  return `/**
 * Auto-generated Zod validators for ${tableName} table
 * Generated by ChittySchema API at schema.chitty.cc
 * DO NOT EDIT
 */

import { z } from 'zod';

/**
 * ${metadata.description}
 * Database: ${metadata.database}
 * Owner: ${metadata.owner}
 */
export const ${schemaName}Schema = z.object({
${shape}
});

export const ${schemaName}InsertSchema = ${schemaName}Schema.omit({ id: true });
export const ${schemaName}UpdateSchema = ${schemaName}Schema.partial().required({ id: true });

export type ${schemaName} = z.infer<typeof ${schemaName}Schema>;
export type ${schemaName}Insert = z.infer<typeof ${schemaName}InsertSchema>;
export type ${schemaName}Update = z.infer<typeof ${schemaName}UpdateSchema>;
`;
}

function tsType(kind?: string): string {
  switch (kind) {
    case 'uuid':
    case 'string':
      return 'string';
    case 'datetime':
    case 'date':
      return 'Date | string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'object':
    case 'record':
      return 'Record<string, any>';
    case 'array':
      return 'any[]';
    case 'bigint':
      return 'bigint';
    default:
      return 'any';
  }
}

function zodType(kind?: string): string {
  switch (kind) {
    case 'uuid':
      return 'z.string().uuid()';
    case 'string':
      return 'z.string()';
    case 'datetime':
      return 'z.union([z.date(), z.string().datetime()])';
    case 'date':
      return 'z.coerce.date()';
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'object':
    case 'record':
      return 'z.record(z.any())';
    case 'array':
      return 'z.array(z.any())';
    case 'bigint':
      return 'z.bigint()';
    default:
      return 'z.any()';
  }
}

function pyType(kind?: string): string {
  switch (kind) {
    case 'uuid':
      return 'UUID';
    case 'string':
      return 'str';
    case 'datetime':
    case 'date':
      return 'datetime';
    case 'number':
      return 'float';
    case 'boolean':
      return 'bool';
    case 'object':
    case 'record':
      return 'dict';
    case 'array':
      return 'list';
    case 'bigint':
      return 'int';
    default:
      return 'Any';
  }
}
