/**
 * Code Generators
 * Generate Pydantic, TypeScript, and Zod from table metadata
 */

interface TableMetadata {
  database: string;
  owner: string;
  columns: any[];
  description: string;
}

/**
 * Generate Pydantic model for Python
 */
export function generatePydanticModel(tableName: string, metadata: TableMetadata): string {
  const className = tableName
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  // Generic model for other tables. We refuse to emit a stub-with-TODO
  // model — that would ship a placeholder downstream. If introspection
  // hasn't yielded columns for this table, fail loud so the caller knows
  // to run `npm run introspect` (or fix the validator generation) first.
  if (!Array.isArray(metadata.columns) || metadata.columns.length === 0) {
    throw new Error(
      `generatePydanticModel: no columns metadata for ${tableName}. ` +
        `Run schema introspection / validator generation before requesting ` +
        `generated types.`
    );
  }
  const fields = metadata.columns
    .map(
      (c) =>
        `    ${c.name}: ${pyType(c.type)}${c.optional || c.nullable ? ' | None' : ''}`
    )
    .join('\n');

  return `"""
Auto-generated Pydantic model for ${tableName} table
Generated by ChittySchema API at schema.chitty.cc
"""

from datetime import datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel


class ${className}(BaseModel):
    """
    ${metadata.description}
    Database: ${metadata.database}
    Owner: ${metadata.owner}
    """
${fields}

    class Config:
        from_attributes = True
`;
}

/**
 * Generate TypeScript types
 */
export function generateTypeScript(tableName: string, metadata: TableMetadata): string {
  const interfaceName = tableName
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  if (!Array.isArray(metadata.columns) || metadata.columns.length === 0) {
    throw new Error(
      `generateTypeScript: no columns metadata for ${tableName}. ` +
        `Run schema introspection / validator generation before requesting ` +
        `generated types.`
    );
  }
  const fields = metadata.columns
    .map(
      (c) =>
        `  ${c.name}${c.optional ? '?' : ''}: ${tsType(c.type)}${c.nullable ? ' | null' : ''};`
    )
    .join('\n');

  return `/**
 * Auto-generated TypeScript types for ${tableName} table
 * Generated by ChittySchema API at schema.chitty.cc
 * DO NOT EDIT
 */

/**
 * ${metadata.description}
 * Database: ${metadata.database}
 * Owner: ${metadata.owner}
 */
export interface ${interfaceName} {
${fields}
}

export type ${interfaceName}Insert = Omit<${interfaceName}, 'id'>;
export type ${interfaceName}Update = Partial<${interfaceName}> & Pick<${interfaceName}, 'id'>;
`;
}

/**
 * Generate Zod validation schema
 */
export function generateZodSchema(tableName: string, metadata: TableMetadata): string {
  const schemaName = tableName
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

  if (!Array.isArray(metadata.columns) || metadata.columns.length === 0) {
    throw new Error(
      `generateZodSchema: no columns metadata for ${tableName}. ` +
        `Run schema introspection / validator generation before requesting ` +
        `generated types.`
    );
  }
  const shape = metadata.columns
    .map(
      (c) =>
        `  ${c.name}: ${zodType(c.type)}${c.nullable ? '.nullable()' : ''}${c.optional ? '.optional()' : ''}`
    )
    .join(',\n');

  return `/**
 * Auto-generated Zod validators for ${tableName} table
 * Generated by ChittySchema API at schema.chitty.cc
 * DO NOT EDIT
 */

import { z } from 'zod';

/**
 * ${metadata.description}
 * Database: ${metadata.database}
 * Owner: ${metadata.owner}
 */
export const ${schemaName}Schema = z.object({
${shape}
});

export const ${schemaName}InsertSchema = ${schemaName}Schema.omit({ id: true });
export const ${schemaName}UpdateSchema = ${schemaName}Schema.partial().required({ id: true });

export type ${schemaName} = z.infer<typeof ${schemaName}Schema>;
export type ${schemaName}Insert = z.infer<typeof ${schemaName}InsertSchema>;
export type ${schemaName}Update = z.infer<typeof ${schemaName}UpdateSchema>;
`;
}

function tsType(kind?: string): string {
  switch (kind) {
    case 'uuid':
    case 'string':
      return 'string';
    case 'datetime':
    case 'date':
      return 'Date | string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'object':
    case 'record':
      return 'Record<string, any>';
    case 'array':
      return 'any[]';
    case 'bigint':
      return 'bigint';
    default:
      return 'any';
  }
}

function zodType(kind?: string): string {
  switch (kind) {
    case 'uuid':
      return 'z.string().uuid()';
    case 'string':
      return 'z.string()';
    case 'datetime':
      return 'z.union([z.date(), z.string().datetime()])';
    case 'date':
      return 'z.coerce.date()';
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'object':
    case 'record':
      return 'z.record(z.any())';
    case 'array':
      return 'z.array(z.any())';
    case 'bigint':
      return 'z.bigint()';
    default:
      return 'z.any()';
  }
}

function pyType(kind?: string): string {
  switch (kind) {
    case 'uuid':
      return 'UUID';
    case 'string':
      return 'str';
    case 'datetime':
    case 'date':
      return 'datetime';
    case 'number':
      return 'float';
    case 'boolean':
      return 'bool';
    case 'object':
    case 'record':
      return 'dict';
    case 'array':
      return 'list';
    case 'bigint':
      return 'int';
    default:
      return 'Any';
  }
}
