// Auto-generated types for api_tokens table
// DO NOT EDIT - Generated by chittyschema


/**
 * api_tokens table
 * Owner: chittyauth
 * ChittyAuth: API authentication tokens for service access
 */
export interface ApiTokens {
  id?: string;
  identity_id?: string;
  token_hash: string;
  name: string;
  scopes?: string[];
  status?: string;
  last_used_at?: Date | string;
  expires_at?: Date | string;
  created_at?: Date | string;
}

/**
 * Insert type for api_tokens (excludes auto-generated fields)
 */
export type ApiTokensInsert = Omit<ApiTokens, 
  'id'
>;

/**
 * Update type for api_tokens (all fields optional except id)
 */
export type ApiTokensUpdate = Partial<ApiTokens> & Pick<ApiTokens, 'id'>;
