// Auto-generated types for atomic_facts table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * atomic_facts table
 * Owner: chittyledger
 * ChittyLedger: AI-extracted atomic facts from evidence documents
 */
export interface AtomicFacts {
  id?: string;
  chitty_id: string;
  evidence_id?: string;
  case_id: string;
  asserted_by?: string;
  fact_text: string;
  fact_type: string;
  related_person_id?: string;
  related_place_id?: string;
  related_thing_id?: string;
  related_event_id?: string;
  related_authority_id?: string;
  location_in_document?: string;
  page_number?: number;
  line_number?: number;
  timestamp_in_media?: string;
  classification_level: string;
  certainty_level?: string;
  weight?: number;
  credibility_factors?: string[];
  bias_indicators?: string[];
  supports_fact_ids?: string[];
  contradicts_fact_ids?: string[];
  temporal_sequence?: number;
  logical_dependency_ids?: string[];
  verified?: boolean;
  verified_by?: string;
  verified_at?: Date | string;
  verification_method?: string;
  discoverable?: boolean;
  privileged?: boolean;
  privilege_type?: string;
  extracted_by_ai?: boolean;
  ai_confidence_score?: number;
  ai_model_version?: string;
  human_reviewed?: boolean;
  tags?: string[];
  legal_elements?: string[];
  fact_date?: Date | string;
  fact_time?: string;
  duration?: string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  version_number?: number;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for atomic_facts (excludes auto-generated fields)
 */
export type AtomicFactsInsert = Omit<AtomicFacts, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for atomic_facts (all fields optional except id)
 */
export type AtomicFactsUpdate = Partial<AtomicFacts> & Pick<AtomicFacts, 'id'>;
