// Auto-generated types for audit_log table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * audit_log table
 * Owner: chittyledger
 * ChittyLedger: System-wide immutable audit trail
 */
export interface AuditLog {
  id?: string;
  event_type: string;
  entity_type: string;
  entity_id?: string;
  user_id?: string;
  action: string;
  old_value?: Record<string, any>;
  new_value?: Record<string, any>;
  ip_address?: string;
  user_agent?: string;
  timestamp?: Date | string;
}

/**
 * Insert type for audit_log (excludes auto-generated fields)
 */
export type AuditLogInsert = Omit<AuditLog, 
  'id' | 'timestamp'
>;

/**
 * Update type for audit_log (all fields optional except id)
 */
export type AuditLogUpdate = Partial<AuditLog> & Pick<AuditLog, 'id'>;
