// Auto-generated types for authorities table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * authorities table
 * Owner: unknown
 */
export interface Authorities {
  id?: string;
  chitty_id: string;
  title: string;
  citation?: string;
  authority_type: string;
  sub_type?: string;
  issuing_authority: string;
  jurisdiction_id?: string;
  court_level?: string;
  effective_date?: Date | string;
  expiration_date?: Date | string;
  decision_date?: Date | string;
  publication_date?: Date | string;
  parent_authority_id?: string;
  hierarchy_level?: number;
  precedential_value?: string;
  full_text?: string;
  summary?: string;
  key_holdings?: string[];
  cites_authorities?: string[];
  cited_by_authorities?: string[];
  amended_by_authorities?: string[];
  superseded_by_authority?: string;
  status?: string;
  url?: string;
  access_level?: string;
  verification_status?: string;
  verified_at?: Date | string;
  verified_by?: string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  version_number?: number;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for authorities (excludes auto-generated fields)
 */
export type AuthoritiesInsert = Omit<Authorities, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for authorities (all fields optional except id)
 */
export type AuthoritiesUpdate = Partial<Authorities> & Pick<Authorities, 'id'>;
