// Auto-generated types for discovery_cache_metadata table
// DO NOT EDIT - Generated by chittyschema


/**
 * discovery_cache_metadata table
 * Owner: chittydiscovery
 * ChittyDiscovery: Metadata for KV cache synchronization state
 */
export interface DiscoveryCacheMetadata {
  id?: string;
  cache_key: string;
  last_synced_at?: Date | string;
  sync_source?: string;
  record_count?: number;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for discovery_cache_metadata (excludes auto-generated fields)
 */
export type DiscoveryCacheMetadataInsert = Omit<DiscoveryCacheMetadata, 
  never
>;

/**
 * Update type for discovery_cache_metadata (all fields optional except id)
 */
export type DiscoveryCacheMetadataUpdate = Partial<DiscoveryCacheMetadata> & Pick<DiscoveryCacheMetadata, 'id'>;
