// Auto-generated types for discovered_services table
// DO NOT EDIT - Generated by chittyschema


/**
 * discovered_services table
 * Owner: chittydiscovery
 * ChittyDiscovery: Service discovery records with real-time presence tracking
 */
export interface DiscoveredServices {
  id?: string;
  service_name: string;
  service_type: string;
  /** Unique ChittyID for the service in DID format (did:chitty:...) */
  chitty_id: string;
  endpoint: string;
  version?: string;
  health_check_url?: string;
  /** Service metadata including capabilities, region, tags, etc. */
  metadata?: Record<string, any>;
  /** Last time the service was seen or announced itself */
  last_seen_at?: Date | string;
  first_discovered_at?: Date | string;
  /** How the service was discovered: mdns (local), workers (Durable Objects), registry (ChittyRegistry), cache (KV) */
  discovery_method: string;
  /** Current service status: active, inactive, unknown, error */
  status?: string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for discovered_services (excludes auto-generated fields)
 */
export type DiscoveredServicesInsert = Omit<DiscoveredServices, 
  never
>;

/**
 * Update type for discovered_services (all fields optional except id)
 */
export type DiscoveredServicesUpdate = Partial<DiscoveredServices> & Pick<DiscoveredServices, 'id'>;
