// Auto-generated types for entity_relationships table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * entity_relationships table
 * Owner: unknown
 */
export interface EntityRelationships {
  id?: string;
  chitty_id: string;
  source_entity_type: string;
  source_entity_id: string;
  target_entity_type: string;
  target_entity_id: string;
  relationship_type: string;
  relationship_subtype?: string;
  description?: string;
  strength_score?: number;
  confidence_score?: number;
  supporting_evidence_ids?: string[];
  supporting_fact_ids?: string[];
  contradicting_evidence_ids?: string[];
  discovered_by?: string;
  discovery_method?: string;
  ai_model_version?: string;
  legal_relevance?: string;
  potential_conflicts?: boolean;
  relationship_start_date?: Date | string;
  relationship_end_date?: Date | string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  status?: string;
  verified?: boolean;
  verified_by?: string;
  verified_at?: Date | string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for entity_relationships (excludes auto-generated fields)
 */
export type EntityRelationshipsInsert = Omit<EntityRelationships, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for entity_relationships (all fields optional except id)
 */
export type EntityRelationshipsUpdate = Partial<EntityRelationships> & Pick<EntityRelationships, 'id'>;
