// Auto-generated types for events table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * events table
 * Owner: unknown
 */
export interface Events {
  id?: string;
  chitty_id: string;
  name: string;
  description?: string;
  event_type: string;
  sub_type?: string;
  start_time: Date | string;
  end_time?: Date | string;
  timezone?: string;
  duration_minutes?: number;
  primary_person_id?: string;
  secondary_person_id?: string;
  witness_ids?: string[];
  location_id?: string;
  related_thing_ids?: string[];
  parent_event_id?: string;
  sequence_number?: number;
  amount?: number;
  currency?: string;
  from_account_id?: string;
  to_account_id?: string;
  legal_significance?: string;
  statutory_deadline?: Date | string;
  status?: string;
  outcome?: string;
  outcome_details?: Record<string, any>;
  evidence_ids?: string[];
  document_ids?: string[];
  is_confidential?: boolean;
  confidentiality_level?: string;
  verification_status?: string;
  verified_at?: Date | string;
  verified_by?: string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  version_number?: number;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for events (excludes auto-generated fields)
 */
export type EventsInsert = Omit<Events, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for events (all fields optional except id)
 */
export type EventsUpdate = Partial<Events> & Pick<Events, 'id'>;
