// Auto-generated types for evidence table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * evidence table
 * Owner: chittyledger
 * ChittyLedger: Court-admissible evidence repository
 */
export interface Evidence {
  id?: string;
  chitty_id: string;
  case_id: string;
  thing_id: string;
  evidence_number?: string;
  evidence_type?: string;
  evidence_tier: string;
  weight?: number;
  authentication_method?: string;
  authenticated_by?: string;
  authentication_date?: Date | string;
  chain_of_custody_verified?: boolean;
  custody_hash?: string;
  minting_status?: string;
  block_number?: string;
  transaction_hash?: string;
  offered_date?: Date | string;
  admitted_date?: Date | string;
  admissibility_ruling?: string;
  exclusion_reason?: string;
  foundation_witnesses?: string[];
  foundation_authorities?: string[];
  objections_raised?: string[];
  objection_responses?: string[];
  submitted_by?: string;
  submission_date?: Date | string;
  discovery_date?: Date | string;
  production_request?: string;
  content_summary?: string;
  key_facts_extracted?: string[];
  status?: string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  version_number?: number;
  notes?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for evidence (excludes auto-generated fields)
 */
export type EvidenceInsert = Omit<Evidence, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for evidence (all fields optional except id)
 */
export type EvidenceUpdate = Partial<Evidence> & Pick<Evidence, 'id'>;
