// Auto-generated types for financial_transactions table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * financial_transactions table
 * Owner: chittyledger
 * ChittyLedger: Immutable financial transaction ledger
 */
export interface FinancialTransactions {
  id?: string;
  transaction_id: string;
  user_id?: string;
  case_id?: string;
  transaction_type: TransactionType;
  amount: number;
  currency?: string;
  status?: TransactionStatus;
  payment_method?: string;
  payment_provider_id?: string;
  payment_provider_response?: Record<string, any>;
  description?: string;
  invoice_url?: string;
  receipt_url?: string;
  metadata?: Record<string, any>;
  processed_at?: Date | string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for financial_transactions (excludes auto-generated fields)
 */
export type FinancialTransactionsInsert = Omit<FinancialTransactions, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for financial_transactions (all fields optional except id)
 */
export type FinancialTransactionsUpdate = Partial<FinancialTransactions> & Pick<FinancialTransactions, 'id'>;
