// Auto-generated types for oauth_clients table
// DO NOT EDIT - Generated by chittyschema


/**
 * oauth_clients table
 * Owner: chittyauth
 * ChittyAuth: OAuth 2.0 registered client applications
 */
export interface OauthClients {
  id?: string;
  client_id: string;
  client_secret_hash: string;
  name: string;
  redirect_uris?: Record<string, any>;
  allowed_scopes?: Record<string, any>;
  status?: string;
  created_at?: Date | string;
}

/**
 * Insert type for oauth_clients (excludes auto-generated fields)
 */
export type OauthClientsInsert = Omit<OauthClients, 
  'id'
>;

/**
 * Update type for oauth_clients (all fields optional except id)
 */
export type OauthClientsUpdate = Partial<OauthClients> & Pick<OauthClients, 'id'>;
