// Auto-generated types for places table
// DO NOT EDIT - Generated by chittyschema

import { BlockchainNetwork, CaseType, ClassificationLevel, EventSeverity, EventType, EvidenceTier, EvidenceType, FactType, SubscriptionStatus, TransactionStatus, TransactionType, UserType } from './enums.js';

/**
 * places table
 * Owner: unknown
 */
export interface Places {
  id?: string;
  chitty_id: string;
  name: string;
  place_type: string;
  sub_type?: string;
  street_address?: string;
  unit_number?: string;
  city?: string;
  state_province?: string;
  postal_code?: string;
  country?: string;
  coordinates?: string;
  elevation?: number;
  timezone?: string;
  parent_place_id?: string;
  jurisdiction_level?: string;
  jurisdiction_code?: string;
  court_type?: string;
  status?: string;
  verification_status?: string;
  verified_at?: Date | string;
  verified_by?: string;
  valid_from?: Date | string;
  valid_to?: Date | string;
  version_number?: number;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
  created_by?: string;
  updated_by?: string;
}

/**
 * Insert type for places (excludes auto-generated fields)
 */
export type PlacesInsert = Omit<Places, 
  'id' | 'valid_from' | 'created_at' | 'updated_at'
>;

/**
 * Update type for places (all fields optional except id)
 */
export type PlacesUpdate = Partial<Places> & Pick<Places, 'id'>;
