// Auto-generated types for semantic_documents table
// DO NOT EDIT - Generated by chittyschema


/**
 * semantic_documents table
 * Owner: unknown
 */
export interface SemanticDocuments {
  id?: string;
  doc_source: string;
  external_id?: string;
  title?: string;
  body?: string;
  metadata?: Record<string, any>;
  embedding?: string;
  search_vector?: string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for semantic_documents (excludes auto-generated fields)
 */
export type SemanticDocumentsInsert = Omit<SemanticDocuments, 
  never
>;

/**
 * Update type for semantic_documents (all fields optional except id)
 */
export type SemanticDocumentsUpdate = Partial<SemanticDocuments> & Pick<SemanticDocuments, 'id'>;
