// Auto-generated types for service_health_history table
// DO NOT EDIT - Generated by chittyschema


/**
 * service_health_history table
 * Owner: chittydiscovery
 * ChittyDiscovery: Historical health check results for discovered services
 */
export interface ServiceHealthHistory {
  id?: string;
  service_id: string;
  checked_at?: Date | string;
  healthy: boolean;
  latency_ms?: number;
  error_message?: string;
  created_at?: Date | string;
}

/**
 * Insert type for service_health_history (excludes auto-generated fields)
 */
export type ServiceHealthHistoryInsert = Omit<ServiceHealthHistory, 
  never
>;

/**
 * Update type for service_health_history (all fields optional except id)
 */
export type ServiceHealthHistoryUpdate = Partial<ServiceHealthHistory> & Pick<ServiceHealthHistory, 'id'>;
