// Auto-generated types for trust_networks table
// DO NOT EDIT - Generated by chittyschema


/**
 * trust_networks table
 * Owner: chittytrust
 * ChittyTrust: Graph of trust relationships between identities
 */
export interface TrustNetworks {
  id?: string;
  identity_a: string;
  identity_b: string;
  trust_score: number;
  relationship: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for trust_networks (excludes auto-generated fields)
 */
export type TrustNetworksInsert = Omit<TrustNetworks, 
  'id'
>;

/**
 * Update type for trust_networks (all fields optional except id)
 */
export type TrustNetworksUpdate = Partial<TrustNetworks> & Pick<TrustNetworks, 'id'>;
