// Auto-generated types for verifications table
// DO NOT EDIT - Generated by chittyschema


/**
 * verifications table
 * Owner: chittyverify
 * ChittyVerify: Historical record of all verification attempts
 */
export interface Verifications {
  id?: string;
  identity_id: string;
  credential_id?: string;
  methods: string[];
  result: boolean;
  trust_score: number;
  confidence?: number;
  risk_factors?: Record<string, any>;
  location?: any;
  ip_address?: string;
  user_agent?: string;
  verified_at?: Date | string;
}

/**
 * Insert type for verifications (excludes auto-generated fields)
 */
export type VerificationsInsert = Omit<Verifications, 
  'id'
>;

/**
 * Update type for verifications (all fields optional except id)
 */
export type VerificationsUpdate = Partial<Verifications> & Pick<Verifications, 'id'>;
