// Auto-generated types for audit_logs table
// DO NOT EDIT - Generated by chittyschema


/**
 * audit_logs table
 * Owner: shared
 * Shared: Audit trail for all ChittyOS operations
 */
export interface AuditLogs {
  id?: string;
  identity_id?: string;
  action: string;
  resource_type: string;
  resource_id?: string;
  details?: Record<string, any>;
  ip_address?: string;
  user_agent?: string;
  created_at?: Date | string;
}

/**
 * Insert type for audit_logs (excludes auto-generated fields)
 */
export type AuditLogsInsert = Omit<AuditLogs, 
  'id' | 'created_at'
>;

/**
 * Update type for audit_logs (all fields optional except id)
 */
export type AuditLogsUpdate = Partial<AuditLogs> & Pick<AuditLogs, 'id'>;
