// Auto-generated types for chronicle_events table
// DO NOT EDIT - Generated by chittyschema


/**
 * chronicle_events table
 * Owner: chittychronicle
 */
export interface ChronicleEvents {
  id?: string;
  timestamp?: Date | string;
  service: string;
  action: string;
  user_id?: string;
  user_email?: string;
  metadata?: Record<string, any>;
  related_events?: string[];
  triggered_by?: string;
  integrations?: string[];
  status?: string;
  error_message?: string;
  search_vector?: string;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for chronicle_events (excludes auto-generated fields)
 */
export type ChronicleEventsInsert = Omit<ChronicleEvents, 
  'id' | 'timestamp' | 'created_at' | 'updated_at'
>;

/**
 * Update type for chronicle_events (all fields optional except id)
 */
export type ChronicleEventsUpdate = Partial<ChronicleEvents> & Pick<ChronicleEvents, 'id'>;
