// Auto-generated types for reception_messages table
// DO NOT EDIT - Generated by chittyschema


/**
 * reception_messages table
 * Owner: chittyreception
 */
export interface ReceptionMessages {
  id?: string;
  identity_id: string;
  message_id: string;
  direction: string;
  from_number: string;
  to_number: string;
  body: string;
  status?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for reception_messages (excludes auto-generated fields)
 */
export type ReceptionMessagesInsert = Omit<ReceptionMessages, 
  'id' | 'created_at' | 'updated_at'
>;

/**
 * Update type for reception_messages (all fields optional except id)
 */
export type ReceptionMessagesUpdate = Partial<ReceptionMessages> & Pick<ReceptionMessages, 'id'>;
