// Auto-generated types for service_validations table
// DO NOT EDIT - Generated by chittyschema


/**
 * service_validations table
 * Owner: unknown
 * ChittyRegister - Validation history for service registration compliance checks.
 */
export interface ServiceValidations {
  chitty_id: string;
  registration_chitty_id?: string;
  service_name: string;
  /** Full validation output. Schema: {"errors": [...], "warnings": [...], "requirements_met": [...], "requirements_failed": [...]}. */
  validation_result: Record<string, any>;
  passed: boolean;
  requirements_version: string;
  validated_at?: Date | string;
}

/**
 * Insert type for service_validations (excludes auto-generated fields)
 */
export type ServiceValidationsInsert = Omit<ServiceValidations, 
  'validated_at'
>;

/**
 * Update type for service_validations (all fields optional)
 */
export type ServiceValidationsUpdate = Partial<ServiceValidations>;
