// Auto-generated types for service_registrations table
// DO NOT EDIT - Generated by chittyschema


/**
 * service_registrations table
 * Owner: unknown
 * ChittyRegister - Service registrations in ChittyOS ecosystem. Owned by ChittyRegister service.
 */
export interface ServiceRegistrations {
  /** ChittyID in format VV-G-LLL-SSSS-T-YM-C-X. Generated by ChittyID service for entity type SERVICE. */
  chitty_id: string;
  service_name: string;
  description: string;
  version: string;
  /** Array of endpoint paths. Schema: ["/health", "/api/v1/status", ...]. Must include /health and /api/v1/status. */
  endpoints: Record<string, any>;
  /** Service schema definition. Schema: {"version": "1.0", "entities": ["PERSON", "TOOL"], "compliance": {...}}. */
  schema: Record<string, any>;
  /** Security configuration. Schema: {"authentication": "jwt|oauth2|apikey", "encryption": "tls|https", "scope": [...]}. */
  security: Record<string, any>;
  status?: string;
  registered_at?: Date | string;
  revoked_at?: Date | string;
  revocation_reason?: string;
  deleted_at?: Date | string;
  deletion_reason?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for service_registrations (excludes auto-generated fields)
 */
export type ServiceRegistrationsInsert = Omit<ServiceRegistrations, 
  'registered_at' | 'created_at' | 'updated_at'
>;

/**
 * Update type for service_registrations (all fields optional)
 */
export type ServiceRegistrationsUpdate = Partial<ServiceRegistrations>;
