// Auto-generated types for service_registration_events table
// DO NOT EDIT - Generated by chittyschema


/**
 * service_registration_events table
 * Owner: unknown
 * ChittyRegister - State transition events for service registration lifecycle tracking.
 */
export interface ServiceRegistrationEvents {
  chitty_id: string;
  registration_chitty_id: string;
  /** Lifecycle event: submitted, validated, certified, published, bound_*, revoked, suspended, reactivated, deleted. */
  event_type: string;
  previous_status?: string;
  new_status: string;
  actor_chitty_id?: string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
}

/**
 * Insert type for service_registration_events (excludes auto-generated fields)
 */
export type ServiceRegistrationEventsInsert = Omit<ServiceRegistrationEvents, 
  'created_at'
>;

/**
 * Update type for service_registration_events (all fields optional)
 */
export type ServiceRegistrationEventsUpdate = Partial<ServiceRegistrationEvents>;
