// Auto-generated types for service_bindings table
// DO NOT EDIT - Generated by chittyschema


/**
 * service_bindings table
 * Owner: unknown
 * ChittyRegister - Bindings to Chronicle, Registry, and Discovery services for ecosystem integration.
 */
export interface ServiceBindings {
  chitty_id: string;
  registration_chitty_id: string;
  /** Ecosystem service type: "chronicle" (audit), "registry" (directory), "discovery" (service mesh). */
  binding_type: string;
  binding_chitty_id?: string;
  url?: string;
  status?: string;
  bound_at?: Date | string;
  error_message?: string;
  retry_count?: number;
  last_retry_at?: Date | string;
  metadata?: Record<string, any>;
  created_at?: Date | string;
  updated_at?: Date | string;
}

/**
 * Insert type for service_bindings (excludes auto-generated fields)
 */
export type ServiceBindingsInsert = Omit<ServiceBindings, 
  'created_at' | 'updated_at'
>;

/**
 * Update type for service_bindings (all fields optional)
 */
export type ServiceBindingsUpdate = Partial<ServiceBindings>;
