// Auto-generated types for trust_scores table
// DO NOT EDIT - Generated by chittyschema


/**
 * trust_scores table
 * Owner: chittyscore
 * ChittyTrust: Historical trust score calculations
 */
export interface TrustScores {
  id?: string;
  identity_id: string;
  base_score: number;
  history_score: number;
  network_score: number;
  risk_penalty: number;
  final_score: number;
  calculation_details?: Record<string, any>;
  calculated_at?: Date | string;
}

/**
 * Insert type for trust_scores (excludes auto-generated fields)
 */
export type TrustScoresInsert = Omit<TrustScores, 
  'id' | 'calculated_at'
>;

/**
 * Update type for trust_scores (all fields optional except id)
 */
export type TrustScoresUpdate = Partial<TrustScores> & Pick<TrustScores, 'id'>;
