import { z } from 'zod';

/**
 * Zod validator for service_registrations table
 * Owner: unknown
 */
export const ServiceRegistrationsSchema = z.object({
  /** ChittyID in format VV-G-LLL-SSSS-T-YM-C-X. Generated by ChittyID service for entity type SERVICE. */
  chitty_id: z.string(),
  service_name: z.string(),
  description: z.string(),
  version: z.string(),
  /** Array of endpoint paths. Schema: ["/health", "/api/v1/status", ...]. Must include /health and /api/v1/status. */
  endpoints: z.record(z.any()),
  /** Service schema definition. Schema: {"version": "1.0", "entities": ["PERSON", "TOOL"], "compliance": {...}}. */
  schema: z.record(z.any()),
  /** Security configuration. Schema: {"authentication": "jwt|oauth2|apikey", "encryption": "tls|https", "scope": [...]}. */
  security: z.record(z.any()),
  status: z.string().optional().nullable(),
  registered_at: z.union([z.date(), z.string().datetime()]).optional().nullable(),
  revoked_at: z.union([z.date(), z.string().datetime()]).optional().nullable(),
  revocation_reason: z.string().optional().nullable(),
  deleted_at: z.union([z.date(), z.string().datetime()]).optional().nullable(),
  deletion_reason: z.string().optional().nullable(),
  metadata: z.record(z.any()).optional().nullable(),
  created_at: z.union([z.date(), z.string().datetime()]).optional().nullable(),
  updated_at: z.union([z.date(), z.string().datetime()]).optional().nullable(),
});

/**
 * Validator for inserting into service_registrations
 */
export const ServiceRegistrationsSchemaInsert = ServiceRegistrationsSchema.omit({
  registered_at: true,
  created_at: true,
  updated_at: true
}).extend({
  registered_at: z.union([z.date(), z.string().datetime()]).optional().nullable(),
  created_at: z.union([z.date(), z.string().datetime()]).optional().nullable(),
  updated_at: z.union([z.date(), z.string().datetime()]).optional().nullable()
});

/**
 * Validator for updating service_registrations
 */
export const ServiceRegistrationsSchemaUpdate = ServiceRegistrationsSchema.partial();

export type ServiceRegistrations = z.infer<typeof ServiceRegistrationsSchema>;
export type ServiceRegistrationsInsert = z.infer<typeof ServiceRegistrationsSchemaInsert>;
export type ServiceRegistrationsUpdate = z.infer<typeof ServiceRegistrationsSchemaUpdate>;